In [2]:
# pip install numpy
# conda install numpy
import numpy as np

In [3]:
arreglo_np_list = np.array( [1,2,3] )
arreglo_np_list

array([1, 2, 3])

In [4]:
arreglo_np_tupla = np.array( (1,2,3) )
arreglo_np_tupla

array([1, 2, 3])

In [5]:
print(type(arreglo_np_list))
print(type(arreglo_np_tupla))
print(arreglo_np_list)
print(arreglo_np_tupla)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[1 2 3]
[1 2 3]


In [6]:
np.ones(4) # [1, 1, 1, 1]

array([1., 1., 1., 1.])

In [7]:
np.ones(10000)

array([1., 1., 1., ..., 1., 1., 1.])

In [8]:
np.zeros(1)

array([0.])

In [9]:
np.zeros(5000)

array([0., 0., 0., ..., 0., 0., 0.])

In [10]:
uno = np.ones(1)
uno

array([1.])

In [11]:
print(type(uno[0]))

<class 'numpy.float64'>


In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.ones([3, 2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
np.ones( (2, 3, 4) )

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [17]:
np.ones((2, 3, 4)).shape

(2, 3, 4)